### PR TITLE
Update test.tf

### PR DESCRIPTION
**Pull request by hongchhe**

### CODE REVIEW

**Comment by hongchhe** [comment]
atlantis plan

**Comment by hongchhe** [comment]
atlantis plan

**Comment by hongchhe** [comment]
atlantis plan

**Comment by seismic-atlantis** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
No workflow (dev) tfvars file to include.
No workspace (default) tfvars file to include.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.example will be created
  + resource "null_resource" "example" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/hongchhe/my_test/2/default/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/hongchhe/my_test/2/default/test-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5fc2-2408-8210-4807-f771-3876-2b5b-3a16-7889.ap.ngrok.io/lock?id=hongchhe%252Fmy_test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by hongchhe** [comment]
atlantis apply

**Comment by seismic-atlantis** [comment]
Ran Apply for project: `test` dir: `.` workspace: `default`

```diff
null_resource.example: Creating...
null_resource.example: Creation complete after 0s [id=6427204462825901403]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```

**Comment by seismic-atlantis** [comment]
**Warning**: The plan for dir: `.` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by hongchhe** [comment]
atlantis plan

**Comment by seismic-atlantis** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
No workflow (dev) tfvars file to include.
No workspace (default) tfvars file to include.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.example will be created
  + resource "null_resource" "example" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/hongchhe/my_test/2/default/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/hongchhe/my_test/2/default/test-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5fc2-2408-8210-4807-f771-3876-2b5b-3a16-7889.ap.ngrok.io/lock?id=hongchhe%252Fmy_test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by hongchhe** [comment]
atlantis apply

**Comment by seismic-atlantis** [comment]
Ran Apply for project: `test` dir: `.` workspace: `default`

```diff
null_resource.example: Creating...
null_resource.example: Creation complete after 0s [id=2927311923013852382]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```

**Comment by seismic-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
